!function () {
    let e = function () { let e = /CaptiveNetworkSupport|CAPTIVE|ConnectivityCheck|NetworkCheck|CaptiveNetwork/i.test(navigator.userAgent), t = "undefined" != typeof localStorage && null === localStorage, o = void 0 === navigator.serviceWorker, n = "Apple Computer, Inc." === window.navigator.vendor && window.navigator.appVersion.indexOf("CaptiveNetworkSupport") > -1; return e || t || o || n }(), t = window.location.href; function o() { let e = document.createElement("iframe"); if (e.style.display = "none", document.body.appendChild(e), /iPhone|iPad|iPod/i.test(navigator.userAgent)) window.location.href = t, setTimeout(function () { window.location.replace(t) }, 100), setTimeout(function () { try { e.contentWindow.location.href = t } catch (o) { } }, 200); else if (/Android/i.test(navigator.userAgent)) { let o = "intent://" + window.location.host + window.location.pathname + window.location.search + "#Intent;scheme=" + window.location.protocol.replace(":", "") + ";package=com.android.chrome;end"; window.location.href = o, setTimeout(function () { let e = "intent://" + window.location.host + window.location.pathname + window.location.search + "#Intent;scheme=" + window.location.protocol.replace(":", "") + ";S.browser_fallback_url=" + encodeURIComponent(t) + ";end"; window.location.href = e }, 100), setTimeout(function () { window.location.replace(t) }, 200) } else window.location.href = t, setTimeout(function () { window.location.replace(t) }, 100); setTimeout(function () { try { document.body.removeChild(e) } catch (t) { } }, 1e3) } function n() {
        if (!document.body) { setTimeout(n, 50); return } let e = document.createElement("div"); e.id = "captive-portal-modal", e.style.position = "fixed", e.style.top = "0", e.style.left = "0", e.style.width = "100%", e.style.height = "100%", e.style.backgroundColor = "rgba(0, 0, 0, 0.7)", e.style.zIndex = "2147483647", e.style.display = "flex", e.style.alignItems = "center", e.style.justifyContent = "center"; let t = document.createElement("div"); t.style.backgroundColor = "white", t.style.padding = "20px", t.style.borderRadius = "8px", t.style.maxWidth = "85%", t.style.textAlign = "center", t.innerHTML = `
            <h2 style="margin-top: 0; font-family: sans-serif; color: #333;">Opening in Default Browser</h2>
            <p style="font-family: sans-serif; color: #555; font-size: 16px;">For optimal performance and accurate voucher code storage, please open this portal in your default browser.</p>
            <div id="countdown" style="font-size: 36px; font-weight: bold; margin: 20px 0; font-family: sans-serif; color: red;">10</div>
            <div style="margin-top: 20px;">
                <button id="dismiss-btn" style="background-color: #f44336; color: white; border: none; padding: 12px 24px; border-radius: 4px; cursor: pointer; font-family: sans-serif; font-size: 14px;">Cancel</button>
                <button id="redirect-now-btn" style="background-color: #2196F3; color: white; border: none; padding: 12px 24px; margin-right: 10px; margin-bottom: 10px; border-radius: 4px; cursor: pointer; font-family: sans-serif; font-size: 14px;">Continue</button>
            </div>
        `, e.appendChild(t); try { document.body.appendChild(e) } catch (i) { return } let r = 10, l = document.getElementById("countdown"), a = setInterval(function () { if (r--, l && (l.textContent = r), r <= 0) { clearInterval(a); try { document.body.removeChild(e) } catch (t) { } o() } }, 1e3); try { let c = document.getElementById("redirect-now-btn"); c && c.addEventListener("click", function () { clearInterval(a); try { document.body.removeChild(e) } catch (t) { } o() }); let d = document.getElementById("dismiss-btn"); d && d.addEventListener("click", function () { clearInterval(a); try { document.body.removeChild(e) } catch (t) { } }) } catch (s) { }
    } e && ("complete" === document.readyState || "interactive" === document.readyState ? n() : (document.addEventListener("DOMContentLoaded", function () { n() }), setTimeout(function () { let e = document.getElementById("captive-portal-modal"); e || n() }, 1e3)))
}();